const data = [
  {
    id: 1,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "Apple",
    kyeWordSearch: "Ноутбук, мак, еир, М1, Air",
    name: "Ноутбук Apple MacBook Air 13 M1 256GB 2020",
    price: 44499,
    totalPrice: 44499,
    count: 1,
    img: "https://content1.rozetka.com.ua/goods/images/big/144249716.jpg",
    article: "123456789",
    color: "Space Gray",
    description: {
      series: "MacBook Air",
      screen: {
        diagonal: "13.3″",
        refreshRate: "60 Гц",
        type: "Retina",
        resolution: "2560x1600",
        coating: "Глянцеве",
      },
      processor: {
        type: "Восьмиядерний Apple M1",
        operatingSystem: "macOS Big Sur",
      },
      ram: {
        size: "8 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "256 ГБ",
        m2Slots: "Без слота M.2",
        sataSlots: "Без відсіків",
      },
      graphics: {
        manufacturer: "Apple",
        type: "Інтегрована",
      },
      case: {
        batteryCapacity: "49.9 Вт год",
        color: "Сірий",
        weight: "1.29 кг",
        batteryFeatures: 
          "До 15 годин роботи в інтернеті через бездротову мережу. До 18 годин під час відтворення фільмів з програми Apple TV. Вбудований літій-полімерний акумулятор ємністю 49.9 Вт год.",
        dimensions: "304.1 x 212.4 x 16.1 мм",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax), IEEE 802.11a/b/g/n/ac",
        bluetooth: "Bluetooth 5.0",
      },
      ports: {
        thunderbolt: "2 x Thunderbolt 3 (USB Type-C 3.1 до 40 Гбіт/с, DisplayPort)",
        audioJack: "1 x 3.5 мм для навушників",
      },
      additionalFeatures: [
        "3 підсвіткою клавіатури",
        "Порт Thunderbolt",
      ],
      countryOfOrigin: "Китай",
      class: "Для роботи та навчання",
      modelYear: "2020",
      type: "Ноутбук",
      extraOptions: [
        "HD-камера FaceTime 720p",
        "Технологія True Tone",
        "SSD-накопичувач PCIe",
        "Touch ID",
        "Стереодинаміки",
        "Широке стерео",
        "Підтримка відтворення контенту у форматі Dolby Atmos",
        "Система з трьох спрямованих мікрофонів",
        "Клавіатура Magic Keyboard з підсвіткою",
        "Датчик зовнішньої освітленості",
        "Трекпад Force Touch",
      ],
      packageContents: [
        "MacBook Air",
        "Адаптер живлення USB-C потужністю 30 Вт",
        "Кабель USB-C для заряджання (2 м)",
      ],
      brandRegistrationCountry: "США",
      warranty: "12 місяців офіційної гарантії від виробника",
    },

  },
  {
    id: 2,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "Apple",
    name: "Ноутбук Apple MacBook Pro 16 M2 Pro 1TB 2023",
    kyeWordSearch: "Ноутбук, MacBook, Pro, M2, 16, 1TB, 2023",
    price: 137999,
    totalPrice: 137999,
    count: 1,
    img: "https://content2.rozetka.com.ua/goods/images/big/377417810.jpg",
    article: "123456788",
    color: "Space Gray",
    description: {
      series: "MacBook Pro",
      screen: {
        diagonal: "16″",
        type: "Liquid Retina XDR",
        resolution: "3456x2234",
        refreshRate: "120 Гц",
        coating: "Глянцевое",
      },
      processor: {
        type: "Десятиядерный Apple M2 Pro",
        operatingSystem: "macOS Ventura",
      },
      ram: {
        size: "16 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "1 ТБ",
      },
      graphics: {
        manufacturer: "Apple",
        type: "Интегрированная",
      },
      case: {
        weight: "2.16 кг",
        dimensions: "355.7 x 248.1 x 16.8 мм",
        batteryFeatures: 
          "До 21 часа воспроизведения видео, встроенный литий-полимерный аккумулятор емкостью 100 Вт·ч.",
        color: "Space Gray",
      },
      connectivity: {
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.3",
      },
      ports: {
        thunderbolt: "3 x Thunderbolt 4 (USB-C)",
        audioJack: "3.5 мм аудиоразъем",
      },
      additionalFeatures: [
        "Подсветка клавиатуры",
        "FaceTime HD камера",
        "Технология True Tone",
      ],
      countryOfOrigin: "Китай",
      class: "Для работы и профессионалов",
      modelYear: "2023",
      type: "Ноутбук",
      extraOptions: [
        "SSD PCIe 4.0",
        "Широкоформатные стереодинамики",
        "Система охлаждения Apple",
        "Touch ID",
      ],
      packageContents: [
        "MacBook Pro",
        "Адаптер питания USB-C 140 Вт",
        "Кабель USB-C",
      ],
      brandRegistrationCountry: "США",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  },
  {
    id: 3,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "Apple",
    name: "Ноутбук Apple MacBook Air 13.6 M2 16/256GB 2022",
    kyeWordSearch: "Ноутбук, MacBook, Air, M2, 13.6, 16GB, 256GB, 2022",
    price: 80999,
    totalPrice: 80999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/318737274.jpg",
    article: "123456787",
    color: "Midnight",
    description: {
      series: "MacBook Air",
      screen: {
        diagonal: "13.6″",
        type: "Liquid Retina",
        resolution: "2560x1664",
        refreshRate: "60 Гц",
        coating: "Глянцевое",
      },
      processor: {
        type: "Восьмиядерный Apple M2",
        operatingSystem: "macOS Ventura",
      },
      ram: {
        size: "16 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "256 ГБ",
      },
      graphics: {
        manufacturer: "Apple",
        type: "Интегрированная",
      },
      case: {
        weight: "1.24 кг",
        dimensions: "304.1 x 215.0 x 11.3 мм",
        batteryFeatures: 
          "До 18 часов автономной работы, литий-полимерный аккумулятор емкостью 52.6 Вт·ч.",
        color: "Midnight",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.3",
      },
      ports: {
        thunderbolt: "2 x Thunderbolt 4 (USB-C)",
        audioJack: "3.5 мм аудиоразъем",
      },
      additionalFeatures: [
        "Подсветка клавиатуры",
        "Touch ID",
        "True Tone",
      ],
      countryOfOrigin: "Китай",
      class: "Для работы и учебы",
      modelYear: "2022",
      type: "Ноутбук",
      extraOptions: [
        "FaceTime HD камера",
        "Трекпад Force Touch",
        "Стереодинамики с поддержкой Spatial Audio",
      ],
      packageContents: [
        "MacBook Air",
        "Адаптер питания USB-C 30 Вт",
        "Кабель USB-C",
      ],
      brandRegistrationCountry: "США",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  },
  
  {
    id: 4,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "Lenovo",
    name: "Ноутбук Lenovo Legion 5 15ITH6H",
    kyeWordSearch: "Ноутбук, Lenovo, Legion, 5, 15ITH6H",
    price: 70999,
    totalPrice: 70999,
    count: 1,
    img: "https://content2.rozetka.com.ua/goods/images/big/320926276.jpg",
    article: "123456786",
    color: "Phantom Blue",
    description: {
      series: "Legion 5",
      screen: {
        diagonal: "15.6″",
        refreshRate: "165 Гц",
        type: "IPS",
        resolution: "1920x1080",
        coating: "Матовая",
      },
      processor: {
        type: "Intel Core i7-11800H",
        operatingSystem: "Windows 11 Home",
      },
      ram: {
        size: "16 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "512 ГБ",
        m2Slots: "2 слота M.2",
        sataSlots: "Без SATA",
      },
      graphics: {
        manufacturer: "NVIDIA",
        type: "GeForce RTX 3060",
      },
      case: {
        batteryCapacity: "80 Вт⋅ч",
        color: "Phantom Blue",
        weight: "2.4 кг",
        batteryFeatures: 
          "До 7 часов автономной работы, поддержка быстрой зарядки Rapid Charge Pro.",
        dimensions: "363 x 260 x 25.75 мм",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.1",
      },
      ports: {
        usb: "4 x USB 3.2 Gen 1",
        hdmi: "1 x HDMI 2.1",
        ethernet: "1 x RJ-45",
        audioJack: "1 x 3.5 мм",
      },
      additionalFeatures: [
        "Подсветка клавиатуры RGB",
        "Стереодинамики Harman с Dolby Atmos",
      ],
      countryOfOrigin: "Китай",
      class: "Игровой ноутбук",
      modelYear: "2021",
      type: "Ноутбук",
      extraOptions: [
        "Система охлаждения Coldfront 3.0",
        "Web-камера с механической шторкой",
        "Поддержка NVIDIA DLSS",
      ],
      packageContents: [
        "Ноутбук Lenovo Legion 5",
        "Зарядное устройство 230 Вт",
        "Руководство пользователя",
      ],
      brandRegistrationCountry: "Китай",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  },
  
  {
    id: 5,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "Lenovo",
    name: "Ноутбук Lenovo ideaPad 3 15IGL05",
    kyeWordSearch: "Ноутбук, Lenovo, ideaPad, 3, 15IGL05",
    price: 15999,
    totalPrice: 15999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/286070979.jpg",
    article: "123456785",
    color: "Black",
    description: {
      series: "ideaPad 3",
      screen: {
        diagonal: "15.6″",
        refreshRate: "60 Гц",
        type: "TN",
        resolution: "1366x768",
        coating: "Матовая",
      },
      processor: {
        type: "Intel Celeron N4020",
        operatingSystem: "Windows 10 Home",
      },
      ram: {
        size: "4 ГБ",
      },
      storage: {
        type: "HDD",
        capacity: "1 ТБ",
        m2Slots: "Без M.2 слота",
        sataSlots: "1 слот SATA",
      },
      graphics: {
        manufacturer: "Intel",
        type: "Integrated UHD Graphics 600",
      },
      case: {
        batteryCapacity: "35 Вт⋅ч",
        color: "Black",
        weight: "1.85 кг",
        batteryFeatures: 
          "До 6 часов работы в режиме веб-серфинга.",
        dimensions: "362.2 x 253.4 x 19.9 мм",
      },
      connectivity: {
        wifi: "Wi-Fi 5 (802.11ac)",
        bluetooth: "Bluetooth 5.0",
      },
      ports: {
        usb: "2 x USB 3.1 Gen 1, 1 x USB 2.0",
        hdmi: "1 x HDMI 1.4b",
        ethernet: "1 x RJ-45",
        audioJack: "1 x 3.5 мм",
      },
      additionalFeatures: [
        "Камера с разрешением 0.3 МП",
        "Микрофон с шумоподавлением",
      ],
      countryOfOrigin: "Китай",
      class: "Для офиса и учёбы",
      modelYear: "2021",
      type: "Ноутбук",
      extraOptions: [
        "Технология Lenovo Vantage",
        "Поддержка Dolby Audio",
      ],
      packageContents: [
        "Ноутбук Lenovo ideaPad 3",
        "Зарядное устройство 65 Вт",
        "Руководство пользователя",
      ],
      brandRegistrationCountry: "Китай",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  },
  
  {
    id: 6,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "Lenovo",
    name: "Ноутбук Lenovo ideaPad Gaming 3 15ACH6",
    kyeWordSearch: "Ноутбук, Lenovo, ideaPad, Gaming, 3, 15ACH6",
    price: 45999,
    totalPrice: 45999,
    count: 1,
    img: "https://content2.rozetka.com.ua/goods/images/big/320910753.jpg",
    article: "123456784",
    color: "Shadow Black",
    description: {
      series: "ideaPad Gaming 3",
      screen: {
        diagonal: "15.6″",
        refreshRate: "120 Гц",
        type: "IPS",
        resolution: "1920x1080",
        coating: "Матовая",
      },
      processor: {
        type: "AMD Ryzen 5 5600H",
        operatingSystem: "Windows 11 Home",
      },
      ram: {
        size: "8 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "512 ГБ",
        m2Slots: "1 слот M.2",
        sataSlots: "1 слот SATA",
      },
      graphics: {
        manufacturer: "NVIDIA",
        type: "GeForce GTX 1650",
      },
      case: {
        batteryCapacity: "45 Вт⋅ч",
        color: "Shadow Black",
        weight: "2.2 кг",
        batteryFeatures: 
          "До 6 часов работы при средней нагрузке.",
        dimensions: "359.6 x 253.4 x 23.9 мм",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.0",
      },
      ports: {
        usb: "2 x USB 3.2 Gen 1, 1 x USB 2.0",
        hdmi: "1 x HDMI 2.0",
        ethernet: "1 x RJ-45",
        audioJack: "1 x 3.5 мм",
      },
      additionalFeatures: [
        "Подсветка клавиатуры",
        "Аудио с технологией Dolby Audio",
        "Поддержка быстрой зарядки",
      ],
      countryOfOrigin: "Китай",
      class: "Для игр и работы",
      modelYear: "2021",
      type: "Ноутбук",
      extraOptions: [
        "Технология Lenovo Vantage",
        "Поддержка Dolby Audio",
        "Игровая клавиатура с подсветкой",
      ],
      packageContents: [
        "Ноутбук Lenovo ideaPad Gaming 3",
        "Зарядное устройство 65 Вт",
        "Руководство пользователя",
      ],
      brandRegistrationCountry: "Китай",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  },
  
  {
    id: 7,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "ASUS",
    name: "Ноутбук ASUS TUF Gaming A15 nVidia GeForce RTX 3050",
    kyeWordSearch: "Ноутбук, ASUS, TUF Gaming, A15, nVidia, GeForce, RTX 3050",
    price: 40999,
    totalPrice: 40999,
    count: 1,
    img: "https://content1.rozetka.com.ua/goods/images/big/302686477.jpg",
    article: "123456783",
    color: "Graphite Black",
    description: {
      series: "TUF Gaming A15",
      screen: {
        diagonal: "15.6″",
        refreshRate: "144 Гц",
        type: "IPS",
        resolution: "1920x1080",
        coating: "Матовая",
      },
      processor: {
        type: "AMD Ryzen 7 5800H",
        operatingSystem: "Windows 11 Home",
      },
      ram: {
        size: "16 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "512 ГБ",
        m2Slots: "1 слот M.2",
        sataSlots: "1 слот SATA",
      },
      graphics: {
        manufacturer: "NVIDIA",
        type: "GeForce RTX 3050",
      },
      case: {
        batteryCapacity: "90 Вт⋅ч",
        color: "Graphite Black",
        weight: "2.3 кг",
        batteryFeatures: 
          "До 8 часов работы при средней нагрузке.",
        dimensions: "359 x 256 x 23.5 мм",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.1",
      },
      ports: {
        usb: "2 x USB 3.2 Gen 1, 1 x USB Type-C",
        hdmi: "1 x HDMI 2.0",
        ethernet: "1 x RJ-45",
        audioJack: "1 x 3.5 мм",
      },
      additionalFeatures: [
        "Подсветка клавиатуры",
        "Поддержка технологии Dolby Atmos",
        "Встроенные стереодинамики",
      ],
      countryOfOrigin: "Тайвань",
      class: "Для игр",
      modelYear: "2022",
      type: "Ноутбук",
      extraOptions: [
        "Технология Anti-Dust Cooling",
        "Поддержка технологии GamePlus",
      ],
      packageContents: [
        "Ноутбук ASUS TUF Gaming A15",
        "Зарядное устройство 200 Вт",
        "Руководство пользователя",
      ],
      brandRegistrationCountry: "Тайвань",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  },
  
  {
    id: 8,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "ASUS",
    name: "Ноутбук ASUS TUF Gaming F15 nVidia GeForce GTX 1650",
    kyeWordSearch: "Ноутбук, ASUS, TUF Gaming, F15, nVidia, GeForce, GTX 1650",
    price: 30999,
    totalPrice: 30099,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/315016995.jpg",
    article: "123456782",
    color: "Bonfire Black",
    description: {
      series: "TUF Gaming F15",
      screen: {
        diagonal: "15.6″",
        refreshRate: "60 Гц",
        type: "IPS",
        resolution: "1920x1080",
        coating: "Матовая",
      },
      processor: {
        type: "Intel Core i5-11400H",
        operatingSystem: "Windows 11 Home",
      },
      ram: {
        size: "8 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "512 ГБ",
        m2Slots: "1 слот M.2",
        sataSlots: "1 слот SATA",
      },
      graphics: {
        manufacturer: "NVIDIA",
        type: "GeForce GTX 1650",
      },
      case: {
        batteryCapacity: "48 Вт⋅ч",
        color: "Bonfire Black",
        weight: "2.2 кг",
        batteryFeatures: 
          "До 5 часов работы при средней нагрузке.",
        dimensions: "359 x 256 x 24 мм",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.0",
      },
      ports: {
        usb: "2 x USB 3.2 Gen 1, 1 x USB Type-C",
        hdmi: "1 x HDMI 2.0",
        ethernet: "1 x RJ-45",
        audioJack: "1 x 3.5 мм",
      },
      additionalFeatures: [
        "Подсветка клавиатуры",
        "Антибактериальные кнопки",
        "Поддержка технологии Dolby Audio",
      ],
      countryOfOrigin: "Тайвань",
      class: "Для игр",
      modelYear: "2022",
      type: "Ноутбук",
      extraOptions: [
        "Технология GameFast",
        "Технология TUF Gaming",
      ],
      packageContents: [
        "Ноутбук ASUS TUF Gaming F15",
        "Зарядное устройство 150 Вт",
        "Руководство пользователя",
      ],
      brandRegistrationCountry: "Тайвань",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  },
  
  {
    id: 9,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "ASUS",
    name: "Ноутбук Asus ROG Strix G15 / Ryzen 7 / RTX 3050",
    kyeWordSearch: "Ноутбук, Asus, ROG Strix, G15, Ryzen 7, RTX 3050",
    price: 39999,
    totalPrice: 39999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/315861665.jpg",
    article: "123456781",
    color: "Eclipse Gray",
    description: {
      series: "ROG Strix G15",
      screen: {
        diagonal: "15.6″",
        refreshRate: "144 Гц",
        type: "IPS",
        resolution: "1920x1080",
        coating: "Гладкое",
      },
      processor: {
        type: "AMD Ryzen 7 5800H",
        operatingSystem: "Windows 11 Home",
      },
      ram: {
        size: "16 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "512 ГБ",
        m2Slots: "1 слот M.2",
        sataSlots: "1 слот SATA",
      },
      graphics: {
        manufacturer: "NVIDIA",
        type: "GeForce RTX 3050",
      },
      case: {
        batteryCapacity: "66 Вт⋅ч",
        color: "Eclipse Gray",
        weight: "2.4 кг",
        batteryFeatures: 
          "До 7 часов работы при средней нагрузке.",
        dimensions: "360 x 260 x 25 мм",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.1",
      },
      ports: {
        usb: "2 x USB 3.2 Gen 1, 1 x USB Type-C",
        hdmi: "1 x HDMI 2.0",
        ethernet: "1 x RJ-45",
        audioJack: "1 x 3.5 мм",
      },
      additionalFeatures: [
        "RGB подсветка клавиатуры",
        "Поддержка Dolby Vision",
        "Поддержка технологии GameFast",
      ],
      countryOfOrigin: "Тайвань",
      class: "Для игр",
      modelYear: "2022",
      type: "Ноутбук",
      extraOptions: [
        "Технология Adaptive Sync",
        "Поддержка технологии GamePlus",
      ],
      packageContents: [
        "Ноутбук Asus ROG Strix G15",
        "Зарядное устройство 200 Вт",
        "Руководство пользователя",
      ],
      brandRegistrationCountry: "Тайвань",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  },
  
  {
    id: 10,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "MSI",
    name: "Ноутбук MSI GF63 Thin / Intel Core i7 / GTX 1650",
    kyeWordSearch: "Ноутбук, MSI, GF63, Thin, Intel Core i7, GTX 1650",
    price: 34999,
    totalPrice: 34999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/309034188.jpg",
    article: "123456780",
    color: "Black",
    description: {
      series: "GF63 Thin",
      screen: {
        diagonal: "15.6″",
        refreshRate: "60 Гц",
        type: "IPS",
        resolution: "1920x1080",
        coating: "Гладкое",
      },
      processor: {
        type: "Intel Core i7-11800H",
        operatingSystem: "Windows 10 Home",
      },
      ram: {
        size: "8 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "512 ГБ",
        m2Slots: "1 слот M.2",
        sataSlots: "1 слот SATA",
      },
      graphics: {
        manufacturer: "NVIDIA",
        type: "GeForce GTX 1650",
      },
      case: {
        batteryCapacity: "51 Вт⋅ч",
        color: "Black",
        weight: "1.86 кг",
        batteryFeatures: 
          "До 5 часов работы при средней нагрузке.",
        dimensions: "359 x 254 x 21.7 мм",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.1",
      },
      ports: {
        usb: "2 x USB 3.2 Gen 1, 1 x USB Type-C",
        hdmi: "1 x HDMI 2.0",
        ethernet: "1 x RJ-45",
        audioJack: "1 x 3.5 мм",
      },
      additionalFeatures: [
        "Подсветка клавиатуры",
        "Поддержка технологии Nahimic 3D Audio",
        "Поддержка технологии Cooler Boost",
      ],
      countryOfOrigin: "Тайвань",
      class: "Для игр",
      modelYear: "2021",
      type: "Ноутбук",
      extraOptions: [
        "Оптимизация для игр",
        "Технология MSI Dragon Center",
      ],
      packageContents: [
        "Ноутбук MSI GF63 Thin",
        "Зарядное устройство 150 Вт",
        "Руководство пользователя",
      ],
      brandRegistrationCountry: "Тайвань",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  },  
  {
    id: 11,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "HP",
    name: "Ноутбук HP Pavilion x360 / Intel Core i5 / 8GB RAM / 512GB SSD",
    kyeWordSearch: "Ноутбук, HP, Pavilion, x360, Intel Core i5, 8GB RAM, 512GB SSD",
    price: 28999,
    totalPrice: 28999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/290944694.jpg",
    article: "123456779",
    color: "Silver",
    description: {
      series: "Pavilion x360",
      screen: {
        diagonal: "14″",
        refreshRate: "60 Гц",
        type: "IPS",
        resolution: "1920x1080",
        coating: "Гладкое",
      },
      processor: {
        type: "Intel Core i5-1135G7",
        operatingSystem: "Windows 11 Home",
      },
      ram: {
        size: "8 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "512 ГБ",
        m2Slots: "1 слот M.2",
        sataSlots: "0",
      },
      graphics: {
        manufacturer: "Intel",
        type: "Intel Iris Xe",
      },
      case: {
        batteryCapacity: "41 Вт⋅ч",
        color: "Silver",
        weight: "1.6 кг",
        batteryFeatures: 
          "До 8 часов работы при средней нагрузке.",
        dimensions: "324 x 227 x 19.9 мм",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.0",
      },
      ports: {
        usb: "2 x USB 3.2 Gen 1, 1 x USB Type-C",
        hdmi: "1 x HDMI 2.0",
        ethernet: "Нет",
        audioJack: "1 x 3.5 мм",
      },
      additionalFeatures: [
        "Подсветка клавиатуры",
        "Поворотный экран 360°",
        "Поддержка Windows Ink",
      ],
      countryOfOrigin: "Китай",
      class: "Для работы и учёбы",
      modelYear: "2021",
      type: "Ноутбук",
      extraOptions: [
        "Долговечная батарея",
        "Технология Bang & Olufsen",
      ],
      packageContents: [
        "Ноутбук HP Pavilion x360",
        "Зарядное устройство 65 Вт",
        "Руководство пользователя",
      ],
      brandRegistrationCountry: "Китай",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  },
  
  {
    id: 12,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    brend: "Lenovo",
    name: "Ноутбук Lenovo Legion 5 / Ryzen 7 / GTX 1660 Ti",
    kyeWordSearch: "Ноутбук, Lenovo, Legion 5, Ryzen 7, GTX 1660 Ti",
    price: 41999,
    totalPrice: 41999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/320954709.jpg",
    article: "123456778",
    color: "Black",
    description: {
      series: "Legion 5",
      screen: {
        diagonal: "15.6″",
        refreshRate: "120 Гц",
        type: "IPS",
        resolution: "1920x1080",
        coating: "Гладкое",
      },
      processor: {
        type: "AMD Ryzen 7 4800H",
        operatingSystem: "Windows 10 Home",
      },
      ram: {
        size: "16 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "512 ГБ",
        m2Slots: "1 слот M.2",
        sataSlots: "1 слот SATA",
      },
      graphics: {
        manufacturer: "NVIDIA",
        type: "GeForce GTX 1660 Ti",
      },
      case: {
        batteryCapacity: "60 Вт⋅ч",
        color: "Black",
        weight: "2.3 кг",
        batteryFeatures: 
          "До 6 часов работы при средней нагрузке.",
        dimensions: "363 x 259 x 24 мм",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.0",
      },
      ports: {
        usb: "2 x USB 3.2 Gen 1, 1 x USB Type-C",
        hdmi: "1 x HDMI 2.0",
        ethernet: "1 x RJ-45",
        audioJack: "1 x 3.5 мм",
      },
      additionalFeatures: [
        "Подсветка клавиатуры",
        "Технология Lenovo Vantage",
        "Поддержка Dolby Audio",
      ],
      countryOfOrigin: "Китай",
      class: "Для игр",
      modelYear: "2021",
      type: "Ноутбук",
      extraOptions: [
        "Технология Coldfront 2.0",
        "Технология Game Mode",
      ],
      packageContents: [
        "Ноутбук Lenovo Legion 5",
        "Зарядное устройство 230 Вт",
        "Руководство пользователя",
      ],
      brandRegistrationCountry: "Китай",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  }, 
  

  {
    id: 13,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    brend: "Apple",
    name: "Apple iPhone 15 Pro 128GB Natural Titanium",
    kyeWordSearch: "Apple iPhone 15 Pro, 128GB, Natural Titanium, iOS, смартфон",
    price: 43499,
    totalPrice: 43499,
    count: 1,
    img: "https://content1.rozetka.com.ua/goods/images/big/364827001.jpg",
    article: "1234",
    color: "Titanium Grey",
    description: {
      series: "iPhone 15 Pro",
      screen: {
        diagonal: "6.1″",
        refreshRate: "120 Гц",
        type: "OLED",
        resolution: "2532x1170",
        coating: "Ceramic Shield",
      },
      processor: {
        type: "Apple A17 Pro",
        operatingSystem: "iOS 17",
      },
      ram: {
        size: "6 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "128 ГБ",
        m2Slots: "0",
        sataSlots: "0",
      },
      graphics: {
        manufacturer: "Apple",
        type: "Apple GPU",
      },
      camera: {
        main: "48 МП",
        ultraWide: "12 МП",
        telephoto: "12 МП",
        front: "12 МП",
        additionalFeatures: [
          "Night Mode",
          "Deep Fusion",
          "Smart HDR 4",
          "ProRAW, ProRes video",
        ],
      },
      battery: {
        capacity: "3200 мА⋅ч",
        charging: "Fast charging, MagSafe, беспроводная зарядка",
        batteryLife: "До 23 часов видео",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        signal: "Поддержка 5G",
      },
      ports: {
        usb: "USB Type-C",
        audioJack: "Отсутствует",
      },
      additionalFeatures: [
        "Поддержка Face ID",
        "IP68 водо- и пылезащищенность",
        "Технология Dynamic Island",
        "Titanium frame",
      ],
      countryOfOrigin: "Китай",
      class: "Смартфон премиум-класса",
      modelYear: "2023",
      type: "Смартфон",
      extraOptions: [
        "Поддержка MagSafe",
        "Поддержка беспроводной зарядки",
      ],
      packageContents: [
        "iPhone 15 Pro",
        "Кабель USB-C",
        "Инструкция",
      ],
      brandRegistrationCountry: "США",
      warranty: "12 месяцев официальной гарантии от производителя",
    },
  },
  
  {
    id: 14,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    brend: "Apple",
    name: "Apple iPhone 15 Pro 128GB Black Titanium",
    kyeWordSearch: "Apple iPhone 15 Pro, 128GB, Black Titanium, iOS, смартфон",
    price: 43499,
    totalPrice: 43499,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/364824471.jpg",
    article: "1235",
    color: "Titanium Black",
    description: {
      series: "iPhone 15 Pro",
      screen: {
        diagonal: "6.1″",
        refreshRate: "120 Гц",
        type: "OLED",
        resolution: "2532x1170",
        coating: "Ceramic Shield",
      },
      processor: {
        type: "Apple A17 Pro",
        operatingSystem: "iOS 17",
      },
      ram: {
        size: "6 ГБ",
      },
      storage: {
        type: "SSD",
        capacity: "128 ГБ",
        m2Slots: "0",
        sataSlots: "0",
      },
      graphics: {
        manufacturer: "Apple",
        type: "Apple GPU",
      },
      camera: {
        main: "48 МП",
        ultraWide: "12 МП",
        telephoto: "12 МП",
        front: "12 МП",
        additionalFeatures: [
          "Night Mode",
          "Deep Fusion",
          "Smart HDR 4",
          "ProRAW, ProRes video",
        ],
      },
      battery: {
        capacity: "3200 мА⋅ч",
        charging: "Fast charging, MagSafe, беспроводная зарядка",
        batteryLife: "До 23 часов видео",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        signal: "Поддержка 5G",
      },
      ports: {
        usb: "USB Type-C",
        audioJack: "Отсутствует",
      },
      additionalFeatures: [
        "Поддержка Face ID",
        "IP68 водо- и пылезащищенность",
        "Технология Dynamic Island",
        "Titanium frame",
      ],
      countryOfOrigin: "Китай",
      class: "Смартфон премиум-класса",
      modelYear: "2023",
      type: "Смартфон",
      extraOptions: [
        "Поддержка MagSafe",
        "Поддержка беспроводной зарядки",
      ],
      packageContents: [
        "iPhone 15 Pro",
        "Кабель USB-C",
        "Инструкция",
      ],
      brandRegistrationCountry: "США",
      warranty: "12 месяцев официальной гарантии от производителя",
    }
  },
  
  {
    id: 15,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    brend: "Apple",
    name: "Apple iPhone 15 Pro 1TB Black Titanium",
    kyeWordSearch: "Телефон, Apple, Pro, про, 15, Titanium",
    price: 69999,
    totalPrice: 69999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/364834188.jpg",
    article: "1236",
    color: "Titanium Black",
    description: {
        series: "iPhone 15 Pro",
        display: {
            size: "6.1\"",
            resolution: "2532x1170",
            refreshRate: "120Hz",
            type: "Super Retina XDR",
            coating: "Ceramic Shield",
        },
        processor: {
            type: "A17 Pro",
            operatingSystem: "iOS 17",
        },
        storage: {
            capacity: "1 TB",
        },
        camera: {
            rear: "Triple 48 MP (main), 12 MP (ultra-wide), 12 MP (telephoto)",
            front: "12 MP",
            features: [
                "Deep Fusion",
                "Night Mode",
                "ProRAW",
                "ProRes video recording",
                "LiDAR Scanner",
            ],
        },
        connectivity: {
            wifi: "Wi-Fi 6 (802.11ax)",
            bluetooth: "Bluetooth 5.3",
            signal: "5G, 4G LTE",
        },
        ports: {
            lightning: "1 x Lightning",
            audioJack: "Нет",
        },
        battery: {
            capacity: "3200 mAh",
            features: "Быстрая зарядка, беспроводная зарядка MagSafe.",
        },
        additionalFeatures: [
            "Face ID",
            "IP68 water and dust resistance",
            "Dual SIM (Nano-SIM and eSIM)",
            "Spatial audio",
            "Dolby Atmos",
        ],
        countryOfOrigin: "China",
        warranty: "1 год официальной гарантии от производителя",
    },
},

{
  id: 16,
  categoriesId: "phone",
  nameCategories: "Телефоны",
  name: "Apple iPhone 15 Pro Max 1TB Blue Titanium",
  brend: "Apple",
  kyeWordSearch: "Телефон, Apple, Pro, про, iPhone, Titanium",
  price: 75000,
  totalPrice: 75000,
  count: 1,
  img: "https://content.rozetka.com.ua/goods/images/big/364839446.jpg",
  article: "1237",
  color: "Titanium Blue",
  description: {
      series: "iPhone 15 Pro Max",
      display: {
          size: "6.7\"",
          resolution: "2796x1290",
          refreshRate: "120Hz",
          type: "Super Retina XDR",
          coating: "Ceramic Shield",
      },
      processor: {
          type: "A17 Pro",
          operatingSystem: "iOS 17",
      },
      storage: {
          capacity: "1 TB",
      },
      camera: {
          rear: "Triple 48 MP (main), 12 MP (ultra-wide), 12 MP (telephoto)",
          front: "12 MP",
          features: [
              "Deep Fusion",
              "Night Mode",
              "ProRAW",
              "ProRes video recording",
              "LiDAR Scanner",
          ],
      },
      connectivity: {
          wifi: "Wi-Fi 6 (802.11ax)",
          bluetooth: "Bluetooth 5.3",
          signal: "5G, 4G LTE",
      },
      ports: {
          lightning: "1 x Lightning",
          audioJack: "Нет",
      },
      battery: {
          capacity: "4323 mAh",
          features: "Fast charging, MagSafe wireless charging",
      },
      additionalFeatures: [
          "Face ID",
          "IP68 water and dust resistance",
          "Dual SIM (Nano-SIM and eSIM)",
          "Spatial audio",
          "Dolby Atmos",
      ],
      countryOfOrigin: "China",
      warranty: "1 год официальной гарантии от производителя",
  },
}, 

{
  id: 17,
  categoriesId: "phone",
  nameCategories: "Телефоны",
  brend: "Nokia",
  kyeWordSearch: "Телефон, Nokia, нокия, Charcoal",
  name: "Nokia C32 6/128GB Charcoal",
  price: 4499,
  totalPrice: 4499,
  count: 1,
  img: "https://content1.rozetka.com.ua/goods/images/big/367870942.jpg",
  article: "1239",
  color: "Green",
  description: {
      series: "Nokia C32",
      display: {
          size: "6.5\"",
          resolution: "1600x720",
          type: "IPS LCD",
      },
      processor: {
          type: "Unisoc Tiger T606",
          operatingSystem: "Android 13 Go Edition",
      },
      storage: {
          capacity: "128 GB",
          expandable: "microSD up to 256 GB",
      },
      camera: {
          rear: "50 MP (main), 2 MP (depth)",
          front: "8 MP",
          features: [
              "AI-assisted photography",
              "Night mode",
              "Portrait mode",
          ],
      },
      connectivity: {
          wifi: "Wi-Fi 802.11 b/g/n",
          bluetooth: "Bluetooth 5.0",
          signal: "4G LTE",
      },
      ports: {
          usb: "USB Type-C",
          audioJack: "3.5mm",
      },
      battery: {
          capacity: "5000 mAh",
          features: "Fast charging 10W",
      },
      additionalFeatures: [
          "Fingerprint sensor",
          "Face unlock",
          "IP52 water resistance",
      ],
      countryOfOrigin: "India",
      warranty: "1 год официальной гарантии",
  },
}, 

{
  id: 18,
  categoriesId: "phone",
  nameCategories: "Телефоны",
  name: "Samsung Galaxy A14 4/128GB Lime",
  brend: "Samsung",
  kyeWordSearch: "Телефон, Galaxy, самунг, Lime",
  price: 7499,
  totalPrice: 7499,
  count: 1,
  img: "https://content.rozetka.com.ua/goods/images/big/429439912.jpg",
  article: "1241",
  color: "Lime",
  description: {
      series: "Samsung Galaxy A14",
      display: {
          size: "6.6\"",
          resolution: "2408x1080",
          type: "PLS LCD",
      },
      processor: {
          type: "Exynos 850",
          operatingSystem: "Android 13, One UI 5.1",
      },
      storage: {
          capacity: "128 GB",
          expandable: "microSD up to 1 TB",
      },
      camera: {
          rear: "50 MP (main), 2 MP (macro), 2 MP (depth)",
          front: "13 MP",
          features: [
              "AI-enhanced photography",
              "Wide-angle lens",
              "Night mode",
          ],
      },
      connectivity: {
          wifi: "Wi-Fi 802.11 a/b/g/n/ac",
          bluetooth: "Bluetooth 5.0",
          signal: "4G LTE",
      },
      ports: {
          usb: "USB Type-C 2.0",
          audioJack: "3.5mm",
      },
      battery: {
          capacity: "5000 mAh",
          features: "Fast charging 15W",
      },
      additionalFeatures: [
          "Fingerprint scanner",
          "Face unlock",
          "One UI features",
      ],
      countryOfOrigin: "Vietnam",
      warranty: "1 год официальной гарантии",
  },
}, 

{
  id: 19,
  categoriesId: "phone",
  nameCategories: "Телефоны",
  name: "Samsung Galaxy M14 4/64GB Blue",
  brend: "Samsung",
  kyeWordSearch: "Телефон, Galaxy, самсунг, Blue",
  price: 5999,
  totalPrice: 5999,
  count: 1,
  img: "https://content2.rozetka.com.ua/goods/images/big/431618649.jpg",
  article: "1242",
  color: "Blue",
  description: {
      series: "Samsung Galaxy M14",
      display: {
          size: "6.6\"",
          resolution: "2408x1080",
          type: "PLS LCD",
      },
      processor: {
          type: "Exynos 1330",
          operatingSystem: "Android 13, One UI 5.1",
      },
      storage: {
          capacity: "64 GB",
          expandable: "microSD up to 1 TB",
      },
      camera: {
          rear: "50 MP (main), 2 MP (macro), 2 MP (depth)",
          front: "13 MP",
          features: [
              "AI-enhanced photography",
              "Wide-angle lens",
              "Night mode",
          ],
      },
      connectivity: {
          wifi: "Wi-Fi 802.11 a/b/g/n/ac",
          bluetooth: "Bluetooth 5.0",
          signal: "4G LTE",
      },
      ports: {
          usb: "USB Type-C 2.0",
          audioJack: "3.5mm",
      },
      battery: {
          capacity: "6000 mAh",
          features: "Fast charging 15W",
      },
      additionalFeatures: [
          "Fingerprint scanner",
          "Face unlock",
          "One UI features",
      ],
      countryOfOrigin: "Vietnam",
      warranty: "1 год официальной гарантии",
  },
},

{
  id: 20,
  categoriesId: "phones",
  nameCategories: "Телефоны",
  name: "Samsung Galaxy M54 5G 8/256GB Dark Blue",
  brend: "Samsung",
  kyeWordSearch: "Телефон, Galaxy, самсунг, M54, Dark Blue",
  price: 14999,
  totalPrice: 14999,
  count: 1,
  img: "https://content.rozetka.com.ua/goods/images/big/417133239.jpg",
  article: "1243",
  color: "Dark Blue",
  description: {
      series: "Samsung Galaxy M54",
      display: {
          size: "6.7\"",
          resolution: "2400x1080",
          type: "Super AMOLED",
      },
      processor: {
          type: "Exynos 1380",
          operatingSystem: "Android 13, One UI 5.1",
      },
      storage: {
          capacity: "256 GB",
          expandable: "microSD up to 1 TB",
      },
      camera: {
          rear: "108 MP (main), 8 MP (ultrawide), 2 MP (macro)",
          front: "32 MP",
          features: [
              "AI-enhanced photography",
              "Super Steady video",
              "Wide-angle lens",
              "Night mode",
          ],
      },
      connectivity: {
          wifi: "Wi-Fi 802.11 a/b/g/n/ac",
          bluetooth: "Bluetooth 5.3",
          signal: "5G",
      },
      ports: {
          usb: "USB Type-C 2.0",
          audioJack: "3.5mm",
      },
      battery: {
          capacity: "6000 mAh",
          features: "Fast charging 25W",
      },
      additionalFeatures: [
          "Fingerprint scanner",
          "Face unlock",
          "One UI features",
      ],
      countryOfOrigin: "Vietnam",
      warranty: "1 год официальной гарантии",
  },
},

{
  id: 21,
  categoriesId: "phone",
  nameCategories: "Телефоны",
  name: "Телефон Apple iPhone 15 128GB Green",
  brend: "Apple",
  kyeWordSearch: "Телефон, iPhone 15, Apple, Green, 128GB",
  price: 32499,
  totalPrice: 32499,
  count: 1,
  img: "https://content.rozetka.com.ua/goods/images/big/364721029.jpg",
  article: "1244",
  color: "Green",
  description: {
      series: "iPhone 15",
      display: {
          size: "6.1\"",
          resolution: "2532x1170",
          type: "Super Retina XDR OLED",
      },
      processor: {
          type: "Apple A16 Bionic",
          operatingSystem: "iOS 17",
      },
      storage: {
          capacity: "128 GB",
          expandable: "No",
      },
      camera: {
          rear: "48 MP (main), 12 MP (ultrawide)",
          front: "12 MP",
          features: [
              "Night mode",
              "Deep Fusion",
              "Photographic Styles",
              "Cinematic mode",
          ],
      },
      connectivity: {
          wifi: "Wi-Fi 6",
          bluetooth: "Bluetooth 5.3",
          signal: "5G",
      },
      ports: {
          usb: "USB Type-C",
          audioJack: "None",
      },
      battery: {
          capacity: "3279 mAh",
          features: "Fast charging 20W",
      },
      additionalFeatures: [
          "Face ID",
          "IP68 water resistance",
          "Ceramic Shield front cover",
      ],
      countryOfOrigin: "China",
      warranty: "1 год официальной гарантии",
  },
},

{
  id: 22,
  categoriesId: "tablet",
  nameCategories: "Планшеты",
  name: "Планшет Samsung Galaxy Tab S6 Lite 2024 LTE 128GB Gray",
  brend: "Samsung",
  kyeWordSearch: "Планшет, Galaxy Tab, Samsung, Gray, 128GB, LTE",
  price: 14399,
  totalPrice: 14399,
  count: 1,
  img: "https://content1.rozetka.com.ua/goods/images/big/423303148.jpg",
  article: "12341",
  color: "Grey",
  description: {
      series: "Galaxy Tab S6 Lite 2024",
      display: {
          size: "10.4\"",
          resolution: "2000x1200",
          type: "TFT",
      },
      processor: {
          type: "Exynos 9611",
          operatingSystem: "Android 12",
      },
      storage: {
          capacity: "128 GB",
          expandable: "Yes, microSD",
      },
      camera: {
          rear: "8 MP",
          front: "5 MP",
          features: [
              "HDR",
              "Panorama",
              "Video recording",
          ],
      },
      connectivity: {
          wifi: "Wi-Fi 5",
          bluetooth: "Bluetooth 5.0",
          signal: "LTE",
      },
      ports: {
          usb: "USB Type-C",
          audioJack: "3.5mm",
      },
      battery: {
          capacity: "7040 mAh",
          features: "Fast charging 15W",
      },
      additionalFeatures: [
          "S Pen support",
          "Samsung DeX",
          "One UI",
      ],
      countryOfOrigin: "Vietnam",
      warranty: "1 год официальной гарантии",
  },
},
{
  id: 23,
  categoriesId: "tablet",
  nameCategories: "Планшеты",
  name: "Планшет Samsung Galaxy Tab A8 10.5 LTE 64GB Gray",
  brend: "Samsung",
  kyeWordSearch: "Планшет, Galaxy Tab, Samsung, Grey, 64GB, LTE",
  price: 10999,
  totalPrice: 10999,
  count: 1,
  img: "https://content2.rozetka.com.ua/goods/images/big/395136195.jpg",
  article: "12342",
  color: "Grey",
  description: {
      series: "Galaxy Tab A8",
      display: {
          size: "10.5\"",
          resolution: "1920x1200",
          type: "TFT",
      },
      processor: {
          type: "Unisoc T618",
          operatingSystem: "Android 11",
      },
      storage: {
          capacity: "64 GB",
          expandable: "Yes, microSD",
      },
      camera: {
          rear: "8 MP",
          front: "5 MP",
          features: [
              "HDR",
              "Panorama",
              "Video recording",
          ],
      },
      connectivity: {
          wifi: "Wi-Fi 5",
          bluetooth: "Bluetooth 5.0",
          signal: "LTE",
      },
      ports: {
          usb: "USB Type-C",
          audioJack: "3.5mm",
      },
      battery: {
          capacity: "7040 mAh",
          features: "Fast charging 15W",
      },
      additionalFeatures: [
          "Samsung Kids Mode",
          "One UI",
          "Expandable memory",
      ],
      countryOfOrigin: "Vietnam",
      warranty: "1 год официальной гарантии",
  },
},

{
  id: 24,
  categoriesId: "tablet",
  nameCategories: "Планшеты",
  name: "Планшет Apple iPad 10.2 2021 Wi-Fi 64GB Silver",
  brend: "Apple",
  kyeWordSearch: "Планшет, iPad, Apple, Silver, Wi-Fi, 64GB",
  price: 18999,
  totalPrice: 18999,
  count: 1,
  img: "https://content1.rozetka.com.ua/goods/images/big/301654642.jpg",
  article: "12343",
  color: "Silver",
  description: {
      series: "iPad 10.2 2021",
      display: {
          size: "10.2\"",
          resolution: "2160x1620",
          type: "Retina",
      },
      processor: {
          type: "A13 Bionic",
          operatingSystem: "iPadOS 14",
      },
      storage: {
          capacity: "64 GB",
          expandable: "No",
      },
      camera: {
          rear: "8 MP",
          front: "12 MP",
          features: [
              "HDR",
              "Panorama",
              "Video recording",
          ],
      },
      connectivity: {
          wifi: "Wi-Fi 802.11",
          bluetooth: "Bluetooth 4.2",
          signal: "No LTE",
      },
      ports: {
          usb: "Lightning",
          audioJack: "3.5mm",
      },
      battery: {
          capacity: "8827 mAh",
          features: "Fast charging 18W",
      },
      additionalFeatures: [
          "Apple Pencil (1st generation) support",
          "Smart Keyboard support",
          "Touch ID",
      ],
      countryOfOrigin: "China",
      warranty: "1 год официальной гарантии",
  },
}, 

{
  id: 25,
  categoriesId: "tablet",
  nameCategories: "Планшеты",
  name: "Планшет Lenovo Tab M10 HD 2/32 LTE Iron Grey",
  brend: "Lenovo",
  kyeWordSearch: "Планшет, Lenovo, Tab M10, Grey, LTE, 32GB",
  price: 6999,
  totalPrice: 6999,
  count: 1,
  img: "https://content.rozetka.com.ua/goods/images/big/396940448.jpg",
  article: "12344",
  color: "Grey",
  description: {
      series: "Tab M10 HD",
      display: {
          size: "10.1\"",
          resolution: "1280x800",
          type: "IPS LCD",
      },
      processor: {
          type: "MediaTek Helio A22",
          operatingSystem: "Android 10",
      },
      storage: {
          capacity: "32 GB",
          expandable: "MicroSD up to 256GB",
      },
      camera: {
          rear: "5 MP",
          front: "2 MP",
          features: [
              "HDR",
              "Auto-focus",
              "Video recording",
          ],
      },
      connectivity: {
          wifi: "Wi-Fi 802.11 a/b/g/n/ac",
          bluetooth: "Bluetooth 5.0",
          signal: "LTE",
      },
      ports: {
          usb: "Micro USB 2.0",
          audioJack: "3.5mm",
      },
      battery: {
          capacity: "5000 mAh",
          features: "Fast charging 10W",
      },
      additionalFeatures: [
          "Google Assistant",
          "Kids Mode",
          "Dolby Atmos Audio",
      ],
      countryOfOrigin: "China",
      warranty: "1 год официальной гарантии",
  },
}, 

{
  id: 26,
  categoriesId: "tablet",
  nameCategories: "Планшеты",
  name: "Планшет Apple iPad Air 10.9 2022 Wi-Fi 64GB Space Gray",
  brend: "Apple",
  kyeWordSearch: "Планшет, Apple, iPad Air, Space Gray, 64GB, Wi-Fi",
  price: 31999,
  totalPrice: 31999,
  count: 1,
  img: "https://content.rozetka.com.ua/goods/images/big/433662582.jpg",
  article: "12345",
  color: "Space Gray",
  description: {
      series: "iPad Air 10.9",
      display: {
          size: "10.9\"",
          resolution: "2360x1640",
          type: "Liquid Retina",
      },
      processor: {
          type: "Apple M1 Chip",
          operatingSystem: "iPadOS",
      },
      storage: {
          capacity: "64 GB",
          expandable: "No",
      },
      camera: {
          rear: "12 MP",
          front: "12 MP Ultra-Wide",
          features: [
              "Portrait Mode",
              "Center Stage",
              "HDR",
              "Video recording",
          ],
      },
      connectivity: {
          wifi: "Wi-Fi 6",
          bluetooth: "Bluetooth 5.0",
          signal: "Wi-Fi only",
      },
      ports: {
          usb: "USB-C",
          audioJack: "No",
      },
      battery: {
          capacity: "28.6 Wh",
          features: "Up to 10 hours of surfing the web on Wi‑Fi",
      },
      additionalFeatures: [
          "Touch ID",
          "Apple Pencil 2nd Gen support",
          "Smart Keyboard Folio support",
          "True Tone Display",
      ],
      countryOfOrigin: "China",
      warranty: "1 год официальной гарантии",
  },
}

]


export default data