import { store } from "./index";
import { setProducts } from "./productArr/productsSlice";

const products = [
  {
    id: 1,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук Apple MacBook Air 13 M1 256GB 2020",
    price: 44499,
    totalPrice: 44499,
    count: 1,
    img: "https://content1.rozetka.com.ua/goods/images/big/144249716.jpg",
    article: "123456789",
    color: "Space Gray",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 2,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук Apple MacBook Pro 16 M2 Pro 1TB 2023",
    price: 137999,
    totalPrice: 137999,
    count: 1,
    img: "https://content2.rozetka.com.ua/goods/images/big/377417810.jpg",
    article: "123456788",
    color: "Space Gray",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 3,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук Apple MacBook Air 13.6 M2 16/256GB 2022",
    price: 80999,
    totalPrice: 80999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/318737274.jpg",
    article: "123456787",
    color: "Midnight",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 4,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук Lenovo Legion 5 15ITH6H",
    price: 70999,
    totalPrice: 70999,
    count: 1,
    img: "https://content2.rozetka.com.ua/goods/images/big/320926276.jpg",
    article: "123456786",
    color: "Phantom Blue",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 5,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук Lenovo ideaPad 3 15IGL05",
    price: 15999,
    totalPrice: 15999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/286070979.jpg",
    article: "123456785",
    color: "Black",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 6,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук Lenovo ideaPad Gaming 3 15ACH6",
    price: 45999,
    totalPrice: 45999,
    count: 1,
    img: "https://content2.rozetka.com.ua/goods/images/big/320910753.jpg",
    article: "123456784",
    color: "Shadow Black",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 7,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук ASUS TUF Gaming A15 nVidia GeForce RTX 3050",
    price: 40999,
    totalPrice: 40999,
    count: 1,
    img: "https://content1.rozetka.com.ua/goods/images/big/302686477.jpg",
    article: "123456783",
    color: "Graphite Black",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 8,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук ASUS TUF Gaming F15 nVidia GeForce GTX 1650",
    price: 30999,
    totalPrice: 30099,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/315016995.jpg",
    article: "123456782",
    color: "Bonfire Black",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 9,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук Asus ROG Strix G15 / Ryzen 7 / RTX 3050",
    price: 39999,
    totalPrice: 39999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/315861665.jpg",
    article: "123456781",
    color: "Eclipse Gray",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 10,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук Acer Nitro 5 AN517-41-R7K1",
    price: 49999,
    totalPrice: 49999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/309034188.jpg",
    article: "123456791",
    color: "Shale Black",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 11,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук Acer Predator Helios 300",
    price: 68999,
    totalPrice: 68999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/290944694.jpg",
    article: "123456771",
    color: "Abyssal Black",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 12,
    categoriesId: "laptop",
    nameCategories: "Ноутбуки",
    name: "Ноутбук Lenovo Legion 5 Pro",
    price: 67777,
    totalPrice: 67777,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/320954709.jpg",
    article: "123456741",
    color: "Stingray",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },

  {
    id: 13,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    name: "Apple iPhone 15 Pro 128GB Natural Titanium",
    price: 43499,
    totalPrice: 43499,
    count: 1,
    img: "https://content1.rozetka.com.ua/goods/images/big/364827001.jpg",
    article: "1234",
    color: "Titanium Grey",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 14,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    name: "Apple iPhone 15 Pro 128GB Black Titanium",
    price: 43499,
    totalPrice: 43499,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/364824471.jpg",
    article: "1235",
    color: "Titanium Black",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 15,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    name: "Apple iPhone 15 Pro 1TB Black Titanium",
    price: 69999,
    totalPrice: 69999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/364834188.jpg",
    article: "1236",
    color: "Titanium Black",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 16,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    name: "Apple iPhone 15 Pro Max 1TB Blue Titanium",
    price: 75000,
    totalPrice: 75000,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/364839446.jpg",
    article: "1237",
    color: "Titanium Blue",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 17,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    name: "Nokia C32 6/128GB Charcoal",
    price: 4499,
    totalPrice: 4499,
    count: 1,
    img: "https://content1.rozetka.com.ua/goods/images/big/367870942.jpg",
    article: "1239",
    color: "Green",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 18,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    name: "Samsung Galaxy A14 4/128GB Lime",
    price: 7499,
    totalPrice: 7499,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/429439912.jpg",
    article: "1241",
    color: "Lime",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 19,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    name: "Samsung Galaxy M14 4/64GB Blue",
    price: 5999,
    totalPrice: 5999,
    count: 1,
    img: "https://content2.rozetka.com.ua/goods/images/big/431618649.jpg",
    article: "1242",
    color: "Blue",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 20,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    name: "Samsung Galaxy M54 5G 8/256GB Dark Blue",
    price: 14999,
    totalPrice: 14999,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/417133239.jpg",
    article: "1243",
    color: "Dark Blue",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 21,
    categoriesId: "phone",
    nameCategories: "Телефоны",
    name: "Телефон Apple iPhone 15 128GB Green",
    price: 32499,
    totalPrice: 32499,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/364721029.jpg",
    article: "1244",
    color: "Green",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },

  {
    id: 22,
    categoriesId: "tablet",
    nameCategories: "Планшеты",
    name: "Планшет Samsung Galaxy Tab S6 Lite 2024 LTE 128GB Gray",
    price: 14399,
    totalPrice: 14399,
    count: 1,
    img: "https://content1.rozetka.com.ua/goods/images/big/368597137.jpg",
    article: "12341",
    color: "Grey",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 23,
    categoriesId: "tablet",
    nameCategories: "Планшеты",
    name: "Планшет Samsung Galaxy Tab A8 10.5 LTE 64GB Gray",
    price: 10999,
    totalPrice: 10999,
    count: 1,
    img: "https://content2.rozetka.com.ua/goods/images/big/395136195.jpg",
    article: "12342",
    color: "Grey",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 24,
    categoriesId: "tablet",
    nameCategories: "Планшеты",
    name: "Планшет Apple iPad 10.2 2021 Wi-Fi 64GB Silver",
    price: 18999,
    totalPrice: 18999,
    count: 1,
    img: "https://content1.rozetka.com.ua/goods/images/big/409350170.jpg",
    article: "12343",
    color: "Silver",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 25,
    categoriesId: "tablet",
    nameCategories: "Планшеты",
    name: "Планшет Lenovo Tab M10 HD 2/32 LTE Iron Grey",
    price: 6999,
    totalPrice: 6999,
    count: 1,
    img: "https://content2.rozetka.com.ua/goods/images/big/398645005.jpg",
    article: "12344",
    color: "Iron Grey",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 26,
    categoriesId: "tablet",
    nameCategories: "Планшеты",
    name: "Планшет Apple iPad Air 10.9 2022 Wi-Fi 64GB Space Gray",
    price: 31999,
    totalPrice: 31999,
    count: 1,
    img: "https://content2.rozetka.com.ua/goods/images/big/445541659.jpg",
    article: "12345",
    color: "Space Gray",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 27,
    categoriesId: "headphones",
    nameCategories: "Наушники",
    name: "Навушники Defunc True Music TWS Black (D4271M)",
    price: 1199,
    totalPrice: 1199,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/368634951.jpg",
    article: "1112",
    color: "Black",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 28,
    categoriesId: "headphones",
    nameCategories: "Наушники",
    name: "Навушники Samsung Galaxy Buds3 Silver (SM-R530NZAASEK)",
    price: 6199,
    totalPrice: 6199,
    count: 1,
    img: "https://content1.rozetka.com.ua/goods/images/big/449729329.jpg",
    article: "1113",
    color: "Silver",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 29,
    categoriesId: "headphones",
    nameCategories: "Наушники",
    name: "Навушники Apple AirPods Pro with MagSafe Case USB-C",
    price: 10599,
    totalPrice: 10599,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/365137069.jpg",
    article: "1114",
    color: "Silver",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 30,
    categoriesId: "headphones",
    nameCategories: "Наушники",
    name: "Навушники Apple AirPods Max Silver",
    price: 26599,
    totalPrice: 26599,
    count: 1,
    img: "https://content2.rozetka.com.ua/goods/images/big/178058814.jpg",
    article: "1115",
    color: "Silver",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  {
    id: 31,
    categoriesId: "headphones",
    nameCategories: "Наушники",
    name: "Навушники Samsung Galaxy Buds3 Pro White",
    price: 9599,
    totalPrice: 9599,
    count: 1,
    img: "https://content.rozetka.com.ua/goods/images/big/449730509.jpg",
    article: "1115",
    color: "Silver",
    fullDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, rerum et veniam ut, deserunt sapiente voluptate dicta doloremque animi libero cumque porro totam aspernatur eum ipsam quis quaerat dolor amet ea eius officia cum quia, aut asperiores. Aperiam ea eligendi, delectus rem vel similique, ducimus quam accusantium temporibus mollitia dolores assumenda? Cumque quidem vitae delectus ab perspiciatis voluptas autem consequatur ratione vero! Maxime totam consequatur tempora praesentium sit minus voluptates quia rerum. Ipsam, vel aliquam reiciendis esse asperiores velit veniam necessitatibus obcaecati commodi odit tenetur vitae ea iusto iure, in ullam cum nam inventore voluptas sint doloremque suscipit possimus quas dolor. Illum eos tempore vitae iusto qui sint impedit odit repellat atque perferendis! Quibusdam culpa nostrum, doloribus quia, omnis blanditiis laborum aut explicabo nihil tempore ea optio. Placeat temporibus unde dolore sequi dignissimos numquam saepe neque non modi dolor.",
  },
  
];

store.dispatch(setProducts(products));
